services:
  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    networks:
      - app
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - ./client/node_modules/
        - action: rebuild
          path: ./client/package.json
    env_file:
      - ./client/.env.local

  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./server
          action: rebuild

  db:
    image: postgres
    container_name: db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    #expose nginx to outside world - we don't do the same for the client or server because we don't want it accessible to the outside world
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app
    develop:
      watch:
        - action: sync+restart
          path: ./nginx
          target: /etc/nginx/conf.d

volumes:
  db-data:
  pgadmin:

secrets:
  db-password:
    file: db/password.txt

networks:
  app:
    driver: bridge
